- hosts: manager
  vars:
    myapp: apps-ivan
  tasks:
    - name: Install Python
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-docker

    - name: Install module python
      shell: 
        cmd: pip install jsondiff
    
    - name: copy file
      copy:
        src: docker-compose.yml
        dest: /tmp/

    - name: deploy stack
      docker_stack:
        state: present
        name: "{{ myapp }}"
        compose:
          - /tmp/docker-compose.yml

    - name: scale service
      shell:
        cmd: docker service scale apps-ivan_web=4